### ISSUE TITLE
java.lang.SecurityException: class "org.eclipse.jdt.core.compiler.InvalidInputException"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by Empty2k12** [sbt/sbt-java-formatter#16]
I have this error randomly popping up. A week ago this worked fine. Removing the plugin also fixes the error.
```
java.lang.SecurityException: class "org.eclipse.jdt.core.compiler.InvalidInputException"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jdt.core.ToolFactory.createCodeFormatter(ToolFactory.java:173)
	at org.eclipse.jdt.core.ToolFactory.createCodeFormatter(ToolFactory.java:139)
	at com.lightbend.sbt.javaformatter.JavaFormatter$.apply(JavaFormatter.scala:67)
	at com.lightbend.sbt.JavaFormatterPlugin$$anonfun$toBeScopedSettings$2.apply(JavaFormatterPlugin.scala:88)
	at com.lightbend.sbt.JavaFormatterPlugin$$anonfun$toBeScopedSettings$2.apply(JavaFormatterPlugin.scala:76)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by 2m** [comment]
From `0.4.0` this plugin uses Google Java Formatter therefore this issue is obsolete.
